#ident @(#)Makefile	1.9 08/04/06 
###########################################################################
# Sample makefile for installing non-localized auxiliary files
###########################################################################
SRCROOT=	../..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

INSDIR=		include/schily
TARGET=		align.h
XMK_FILE=	\
		align.mk alloca.mk archdefs.mk avoffset.mk btorder.mk \
		ccomdefs.mk checkerr.mk \
		deflts.mk device.mk dirent.mk errno.mk fcntl.mk \
		fetchdir.mk find.mk fnmatch.mk fstream.mk \
		getargs.mk getcwd.mk iconv.mk idcache.mk intcvt.mk ioctl.mk \
		jmpdefs.mk \
		libport.mk librmt.mk maxpath.mk mconfig.mk \
		mman.mk mtio.mk nlsdefs.mk param.mk patmatch.mk prototyp.mk \
		rmtio.mk schily.mk schilyp.mk \
		siconv.mk sigblk.mk signal.mk standard.mk stat.mk \
		stdlib.mk stkframe.mk string.mk termcap.mk termios.mk time.mk \
		types.mk unistd.mk utime.mk utypes.mk varargs.mk \
		walk.mk wchar.mk wait.mk \
		xconfig.mk xmconfig.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.aux
###########################################################################
