.\" @(#)readcd.1	1.29 07/11/27 Copyright 1996-2006 J. Schilling
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License, Version 1.0 only
.\" (the "License").  You may not use this file except in compliance
.\" with the License.
.\"
.\" See the file CDDL.Schily.txt in this distribution for details.
."
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file CDDL.Schily.txt from this distribution.
.\"
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.TH READCD 1 "Version 2.0" "J\*org Schilling" "Schily\'s USER COMMANDS"
.SH NAME
readcd \- read or write data Compact Discs
.SH SYNOPSIS
.B readcd
[
.BI dev= device
][
.I options
]

.SH DESCRIPTION
.B Readcd
is used to read or write Compact Discs.
.PP
The
.I device
refers to
.IR scsibus / target / lun
of the drive. Communication on 
.I SunOS
is done with the SCSI general driver
.B scg.
Other operating systems are using a library simulation of this driver.
Possible syntax is:
.B dev=
.IR scsibus , target , lun
or
.B dev=
.IR target , lun .
In the latter case, the drive has to be connected to the default 
SCSI bus of the machine.
.IR Scsibus ,
.I target 
and 
.I lun
are integer numbers. 
Some operating systems or SCSI transport implementations may require to
specify a filename in addition.
In this case the correct syntax for the device is:
.B dev=
.IR devicename : scsibus , target , lun
or
.B dev=
.IR devicename : target , lun .
If the name of the device node that has been specified on such a system
refers to exactly one SCSI device, a shorthand in the form
.B dev=
.IR devicename : @
or
.B dev=
.IR devicename : @ , lun
may be used instead of
.B dev=
.IR devicename : scsibus , target , lun .

.PP
To access remote SCSI devices, you need to prepend the SCSI device name by
a remote device indicator. The remote device indicator is either
.BI REMOTE: user@host:
or
.BR
.BI REMOTE: host:
.br
A valid remote SCSI device name may be:
.BI REMOTE: user@host:
to allow remote SCSI bus scanning or
.BI REMOTE: user@host:1,0,0
to access the SCSI device at 
.I host
connected to SCSI bus # 1,target 0 lun 0.

.PP
To access SCSI devices via alternate transport layers,
you need to prepend the SCSI device name by a transport layer indicator.
The transport layer indicator may be something like
.B USCSI: 
or
.BR ATAPI: .
To get a list of supported transport layers for your platform, use 
.B dev=
.IR HELP :

.PP
To make 
.B readcd
portable to all \s-2UNIX\s0 platforms, the syntax
.B dev=
.IR devicename : scsibus , target , lun
is preferred as is hides OS specific knowledge about device names from the user.
A specific OS must not necessarily support a way to specify a real device file name nor a
way to specify 
.IR scsibus , target , lun .

.PP
.I Scsibus 
0 is the default SCSI bus on the machine. Watch the boot messages for more 
information or look into 
.B /var/adm/messages 
for more information about the SCSI configuration of your machine.
If you have problems to figure out what values for 
.IR scsibus , target , lun
should be used, try the 
.B \-scanbus
option of 
.BR cdrecord .

.SH OPTIONS
.PP
If no options except the 
.I dev=
option have been specified, 
.B readcd
goes into interactive mode.
Select a primary function and then follow the instructions.
.PP
.TP
.B \-version
Print version information and exit.
.TP
.BI dev= target
Sets the SCSI target for the drive, see notes above.
A typical device specification is
.BI dev= 6,0
\&.
If a filename must be provided together with the numerical target 
specification, the filename is implementation specific.
The correct filename in this case can be found in the system specific
manuals of the target operating system.
On a 
.I FreeBSD
system without 
.I CAM
support, you need to use the control device (e.g.
.IR /dev/rcd0.ctl ).
A correct device specification in this case may be
.BI dev= /dev/rcd0.ctl:@
\&.
.sp
On Linux, drives connected to a parallel port adapter are mapped
to a virtual SCSI bus. Different adapters are mapped to different
targets on this virtual SCSI bus.
.sp
If no 
.I dev
option is present, 
.B cdrecord
will try to get the device from the 
.B CDR_DEVICE
environment.
.sp
If the argument to the
.B dev=
option does not contain the characters ',', '/', '@' or ':',
it is interpreted as an label name that may be found in the file
/etc/default/cdrecord (see FILES section).
.sp
If no 
.B dev=
option is present, or if the
.B dev=
option only contains a transport specifyer but no address,
.B readcd
tries to scan the SCSI address space for CD-ROM drives.
If exactly one is found, this is used by default.
.TP
.BI timeout= #
Set the default SCSI command timeout value to 
.IR # " seconds.
The default SCSI command timeout is the minimum timeout used for sending
SCSI commands.
If a SCSI command fails due to a timeout, you may try to raise the
default SCSI command timeout above the timeout value of the failed command.
If the command runs correctly with a raised command timeout,
please report the better timeout value and the corresponding command to 
the author of the program.
If no 
.I timeout 
option is present, a default timeout of 40 seconds is used.
.TP
.BI debug= "#, " -d
Set the misc debug value to # (with debug=#) or increment
the misc debug level by one (with -d). If you specify
.I -dd,
this equals to 
.BI debug= 2.
This may help to find problems while opening a driver for libscg.
as well as with sector sizes and sector types.
Using
.B \-debug
slows down the process and may be the reason for a buffer underrun.
.TP
.BR kdebug= "#, " kd= #
Tell the 
.BR scg -driver
to modify the kernel debug value while SCSI commands are running.
.TP
.BR \-silent ", " \-s
Do not print out a status report for failed SCSI commands.
.TP
.B \-v
Increment the level of general verbosity by one.
This is used e.g. to display the progress of the process.
.TP
.B \-V
Increment the verbose level with respect of SCSI command transport by one.
This helps to debug problems
during the process, that occur in the CD-Recorder. 
If you get incomprehensible error messages you should use this flag
to get more detailed output.
.B \-VV
will show data buffer content in addition.
Using
.B \-V
or
.B \-VV
slows down the process.
.TP
.BI f= file
Specify the filename where the output should be written or the input should
be taken from. Using '-' as filename will cause
.B readcd
to use 
.BR stdout " resp. " stdin .
.TP
.B \-w
Switch to write mode. If this option is not present,
.B readcd
reads from the specified device.
.TP
.B \-c2scan
Scans the whole CD or the range specified by the 
.BI sectors= range
for C2 errors. C2 errors are errors that are uncorrectable after the second
stage of the 24/28 + 28/32 Reed Solomon correction system at audio level
(2352 bytes sector size). If an audio CD has C2 errors, interpolation is needed
to hide the errors. If a data CD has C2 errors, these errors are in most
cases corrected by the ECC/EDC code that makes 2352 bytes out of 2048 data
bytes. The ECC/EDC code should be able to correct about 100 C2 error bytes
per sector.
.sp
If you find C2 errors you may want to reduce the speed using the
.B speed=
option as C2 errors may be a result of dynamic unbalance on the medium.
.TP
.B \-cxscan
Scans the whole CD or the range specified by the 
.BI sectors= range
for C1/C2/CU errors.
In non-verbose mode, only a summary is printed.
With
.BR \-v ,
a line for each non error free second is printed.
with
.BR \-vv ,
a line for each second is printed.
This scan method only works for a few drives.
.TP
.B \-edc\-corr
In this mode,
.B readcd
reads CD data sectors in uncorrected audio mode 
and then tries to correct the data using the ECC/EDC decoder library
from Heiko Eißfeldt. As this library implements looping over two layers
of error correction, 
.B readcd
may be able to correct more data than the firmware of the CD-ROM drive.
.sp
This option is currently experimental and only applicable with 
CD media and currently only supports
plain 2048 Byte CD-ROM sectors.
.TP
.B \-pi8scan
Scans the whole DVD or the range specified by the 
.BI sectors= range
for 
.B pisum8
errors.
In non-verbose mode, only a summary is printed.
With
.BR \-v ,
a line for each non error free block of 8 * 32 kB is printed.
with
.BR \-vv ,
a line for each block of 8 * 32 kB is printed.
This scan method only works for a few drives.
.TP
.B \-pifscan
Scans the whole DVD or the range specified by the 
.BI sectors= range
for 
.B pif
errors.
In non-verbose mode, only a summary is printed.
With
.BR \-v ,
a line for each non error free block of 32 kB is printed.
with
.BR \-vv ,
a line for each block of 32 kB is printed.
This scan method only works for a few drives.
.TP
.B \-plot
This option modified the behavior for
.BR \-cxscan ,
.BR \-pi8scan 
and
.BR \-pifscan .
The output is better suited for gnuplot.
.TP
.B \-scanbus
Scan all SCSI devices on all SCSI busses and print the inquiry
strings. This option may be used to find SCSI address of the 
devices on a system.
The numbers printed out as labels are computed by: 
.B "bus * 100 + target
.TP
.BI sectors= range
Specify a sector range that should be read.
The range is specified by the starting sector number, a minus sign and the
ending sector number.
The end sector is not included in the list, so 
.BR sectors= 0-0
will not read anything and may be used to check for a CD in the drive.
.TP
.BR speed= #
Set the speed factor of the read or write process to #.
# is an integer, representing a multiple of the audio speed.
This is about 150 KB/s for CD-ROM and about 172 KB/s for CD-Audio.
If no 
.I speed
option is present, 
.B readcd
will use maximum speed.
Only MMC compliant drives will benefit from this option.
The speed of non MMC drives is not changed.
.sp
Using a lower speed may increase the readability of a CD or DVD.
.TP
.BR ts= #
Set the maximum transfer size for a single SCSI command to #.
The syntax for the 
.B ts=
option is the same as for cdrecord fs=# or sdd bs=#.
.sp
If no 
.B ts=
option has been specified,
.B readcd
defaults to a transfer size of 256 kB. If libscg gets lower values from the
operating system, the value is reduced to the maximum value that is possible
with the current operating system.
Sometimes, it may help to further reduce the transfer size or to enhance it,
but note that it may take a long time to find a better value by experimenting
with the
.B ts=
option.
.TP
.B \-notrunc
Do not truncate the output file when opening it.
.TP
.B \-fulltoc
Retrieve a full TOC from the current disk and print it in hex.
.TP
.B \-clone
Do a clone read. Read the CD with all sub-channel data and a full TOC.
The full TOC data will be put into a file with similar name as with the
.B f=
option but the suffix 
.B .toc
added.
.TP
.B \-noerror
Do not abort if the high level error checking in
.B readcd
found an uncorrectable error in the data stream.
.TP
.B \-nocorr
Switch the drive into a mode where it ignores read errors in data sectors that
are a result of uncorrectable ECC/EDC errors before reading.
If
.B readcd
completes, the error recovery mode of the drive is switched back to the remembered 
old mode.
.TP
.BI retries= #
Set the retry count for high level retries in
.B readcd
to 
.IR # .
The default is to do 128 retries which may be too much if you like to read a CD
with many unreadable sectors.
.TP
.B \-overhead
Meter the SCSI command overhead time.
This is done by executing several commands 1000 times and printing the
total time used. If you divide the displayed times by 1000, you get 
the average overhead time for a single command.
.TP
.BR meshpoints= #
Print read-speed at # locations.
The purpose of this option is to create a list of read speed values suitable
for e.g.
.BR gnuplot .
The speed values are calculated assuming that 1000 bytes are one kilobyte
as documented in the SCSI standard.
The output data created for this purpose is written to 
.IR stdout .
.TP
.B \-factor
Output the speed values for
.BR meshpoints= #
as factor based on 
.I "single speed
of the current medium.
This only works if
.B readcd
is able to determine the current medium type.
.SH EXAMPLES
.PP
For all examples below, it will be assumed that the drive is
connected to the primary SCSI bus of the machine. The SCSI target id is
set to 2.
.PP
To read the complete media from a CD-ROM writing the data to the file
.IR cdimage.raw :
.PP
    readcd dev=2,0 f=cdimage.raw
.PP
To read sectors from range 150 ... 10000 from a CD-ROM writing the data to the file
.IR cdimage.raw :
.PP
    readcd dev=2,0 sectors=150-10000 f=cdimage.raw
.PP
To write the data from the file
.I cdimage.raw
(e.g. a filesystem image from 
.BR mkisofs )
to a DVD-RAM, call:
.PP
    readcd dev=2,0 -w f=cdimage.raw

.SH ENVIRONMENT
.TP
.B RSH
If the 
.B RSH
environment is present, the remote connection will not be created via
.BR rcmd (3)
but by calling the program pointed to by
.BR RSH .
Use e.g. 
.BR RSH= /usr/bin/ssh
to create a secure shell connection.
.sp
Note that this forces 
.B cdrecord
to create a pipe to the 
.B rsh(1)
program and disallows
.B cdrecord
to directly access the network socket to the remote server.
This makes it impossible to set up performance parameters and slows down
the connection compared to a 
.B root
initiated
.B rcmd(3)
connection.
.TP
.B RSCSI
If the 
.B RSCSI
environment is present, the remote SCSI server will not be the program
.B /opt/schily/sbin/rscsi
but the program pointed to by
.BR RSCSI .
Note that the remote SCSI server program name will be ignored if you log in
using an account that has been created with a remote SCSI server program as
login shell.
.SH FILES
.SH SEE ALSO
.BR cdrecord (1),
.BR mkisofs (1),
.BR scg (7),
.BR fbk (7),
.BR rcmd (3),
.BR ssh (1).

.SH NOTES
.PP
If you don't want to allow users to become root on your system,
.B readcd
may safely be installed suid root. This allows all users or a group of
users with no root privileges to use 
.B readcd.
.B Readcd
in this case will only allow access to CD-ROM type drives-
To give all user access to use 
.B readcd, 
enter:
.PP
	chown root /usr/local/bin/readcd
.br
	chmod 4711 /usr/local/bin/readcd
.PP
To give a restricted group of users access to 
.B readcd
enter:
.PP
	chown root /usr/local/bin/readcd
.br
	chgrp cdburners /usr/local/bin/readcd
.br
	chmod 4710 /usr/local/bin/readcd
.PP
and add a group 
.I cdburners
on your system.
.PP
Never give write permissions for non root users to the 
.I /dev/scg?
devices unless you would allow anybody to read/write/format
all your disks.
.PP
You should not connect old drives that do not support
disconnect/reconnect to either the SCSI bus that is connected to the
CD-Recorder or the source disk.
.PP
When using 
.B readcd
with the broken 
.B "Linux SCSI generic driver."
You should note that 
.B readcd
uses a hack, that tries to emulate the functionality of the scg driver.
Unfortunately, the sg driver on 
.B Linux
has several severe bugs:
.TP
\(bu
It cannot see if a SCSI command could not be sent at all.
.TP
\(bu
It cannot get the SCSI status byte. 
.B Readcd
for that reason cannot report failing SCSI commands in some
situations.
.TP
\(bu
It cannot get real DMA count of transfer. 
.B Readcd
cannot tell you if there is an DMA residual count.
.TP
\(bu
It cannot get number of bytes valid in auto sense data.
.B Readcd
cannot tell you if device transfers no sense data at all.
.TP
\(bu
It fetches to few data in auto request sense (CCS/SCSI-2/SCSI-3 needs >= 18).

.SH DIAGNOSTICS
.PP
.PP
A typical error message for a SCSI command looks like:
.sp
.RS
.nf
readcd: I/O error. test unit ready: scsi sendcmd: no error
CDB:  00 20 00 00 00 00
status: 0x2 (CHECK CONDITION)
Sense Bytes: 70 00 05 00 00 00 00 0A 00 00 00 00 25 00 00 00 00 00
Sense Key: 0x5 Illegal Request, Segment 0
Sense Code: 0x25 Qual 0x00 (logical unit not supported) Fru 0x0
Sense flags: Blk 0 (not valid)
cmd finished after 0.002s timeout 40s
.fi
.sp
.RE
The first line gives information about the transport of the command.
The text after the first colon gives the error text for the system call
from the view of the kernel. It usually is:
.B "I/O error
unless other problems happen. The next words contain a short description for
the SCSI command that fails. The rest of the line tells you if there were
any problems for the transport of the command over the SCSI bus.
.B "fatal error
means that it was not possible to transport the command (i.e. no device present
at the requested SCSI address).
.PP
The second line prints the SCSI command descriptor block for the failed command.
.PP
The third line gives information on the SCSI status code returned by the 
command, if the transport of the command succeeds. 
This is error information from the SCSI device.
.PP
The fourth line is a hex dump of the auto request sense information for the 
command.
.PP
The fifth line is the error text for the sense key if available, followed
by the segment number that is only valid if the command was a
.I copy
command. If the error message is not directly related to the current command,
the text
.I deferred error
is appended.
.PP
The sixth line is the error text for the sense code and the sense qualifier if available.
If the type of the device is known, the sense data is decoded from tables
in
.IR scsierrs.c " .
The text is followed by the error value for a field replaceable unit.
.PP
The seventh line prints the block number that is related to the failed command
and text for several error flags. The block number may not be valid.
.PP
The eight line reports the timeout set up for this command and the time
that the command really needed to complete.

.SH BUGS

.SH CREDITS

.SH "MAILING LISTS
If you want to actively take part on the development of cdrecord,
you may join the cdwriting mailing list by sending mail to:
.nf
.sp
	other-cdwrite-request@lists.debian.org
.sp
.fi
and include the word 
.I subscribe
in the body.
The mail address of the list is:
.nf
.sp
	cdwrite@lists.debian.org
.fi

.SH AUTHOR
.nf
J\*org Schilling
Seestr. 110
D-13353 Berlin
Germany
.fi
.PP
Additional information can be found on:
.br
http://www.fokus.fhg.de/usr/schilling/cdrecord.html
.PP
If you have support questions, send them to:
.PP
.B
cdrecord-support@berlios.de
.br
or
.B
other-cdwrite@lists.debian.org
.PP
If you have definitely found a bug, send a mail to:
.PP
.B
cdrecord-developers@berlios.de
.br
or
.B
schilling@fokus.fhg.de
.PP
To subscribe, use:
.PP
.B
http://lists.berlios.de/mailman/listinfo/cdrecord-developers 
.br
or
.B
http://lists.berlios.de/mailman/listinfo/cdrecord-support 
